#ifndef KIRIL_IVANOV_MENTOR_S04_10_12_ERROR_CODES
#define KIRIL_IVANOV_MENTOR_S04_10_12_ERROR_CODES

typedef enum Error
{
    NO_ERROR = 0,
    ALLOCATION_ERROR,
    // ...
} Error;

#endif // KIRIL_IVANOV_MENTOR_S04_10_12_ERROR_CODES
